### Server Configuration
server:
  port: 8888
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# ========== Spring Configuration ===========
spring:
  # ========== JPA ===========
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        shoe_sql: true


  # ========== DB ===========
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
  data:
      mongodb:
        uri: mongodb://218.158.49.199:27017/joalarm

# ========== JWT ===========
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400